### PR TITLE
clarify process and difference between PRs, Issues, and Files

### PR DESCRIPTION
**Pull request by campoy**
This should help clarify the process.

- One issue per CfP (following /.github/ISSUE_TEMPLATE.md)
- One PR per talk proposal to a CfP (following /.github/PULL_REQUEST_TEMPLATE.md)
- The PR simply adds a file containing the proposal details (following /.github/PROPOSAL_TEMPLATE.md)

### CODE REVIEW

**Comment by campoy** [comment]
Fixes #2

**Comment by campoy** [comment]
Hey @vmarkovtsev, can you have a look at this and tell me if whether it's more clear now?
Thanks!

**Review by vmarkovtsev — APPROVED** [review]
The issue comment helped, thanks.

Issue - declares the conference and the possibility to speak
PR - concrete talk submissions to that conference

**Comment by campoy** [comment]
Hey @vmarkovtsev, could you approve this PR so I can merge it? haha

**Comment by vmarkovtsev** [comment]
But... "vmarkovtsev approved these changes about 3 hours ago"

**Comment by campoy** [comment]
GitHub permissions

how do they work?

**Pull request merged**
