### PR TITLE
2018/04 - Retina - Awesome Google

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Updates: https://github.com/src-d/conferences/issues/62

### CODE REVIEW

**Review by campoy — APPROVED** [review]

**Comment by campoy** [comment]
Please sign the commit, @vmarkovtsev

**Comment by vmarkovtsev** [comment]
@campoy As was discussed with Eiso, source{d} employees are not required to sign-off their commits. They automatically do so.

**Comment by campoy** [comment]
Argh, we should fix the `DCO` thing so it doesn't complain for employees

@smola, what do you think? In the meanwhile I'll merge

**Comment by smola** [comment]
@campoy https://github.com/src-d/guide/issues/221

**Pull request merged**
