### PR TITLE
2018/05 - PyDays Vienna - Analyzing GitHub, how developers change programming languages over time

### PR DESCRIPTION
**Pull request by warenlg**
Updates: https://github.com/src-d/conferences/issues/54

### CODE REVIEW

**Comment by warenlg** [comment]
This project studies the language competition on GitHub from 2000 to 2015
I really want to expand it to 2018 maybe using the GHTorrent dumps from 2013/10 to 2018/04
http://ghtorrent.org/downloads.html

**Comment by warenlg** [comment]
slides https://warenlg.github.io/pydays-vienna-2018/#

**Comment by campoy** [comment]
Hey @warenlg, could you add the slides to the PR? Then I'll merge it.

**Comment by campoy** [comment]
Hi @warenlg, any luck with the slides?

**Comment by warenlg** [comment]
Really sorry @campoy, this went out of my mind, now fixed !

**Review by vcoisne — APPROVED** [review]
LGTM

**Pull request merged**
