### PR TITLE
2019/04 - DevPRO - Personal code review bots and machine learning on …

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Updates: https://github.com/src-d/conferences/issues/138

### CODE REVIEW

**Comment by vcoisne** [comment]
Sorry I missed this @vmarkovtsev. Might be a good opportunity if all expenses are covered and assuming you have no conflicts with other commitments/deadlines. Abstract LGTM.

**Comment by vmarkovtsev** [comment]
@vcoisne Yes, accepted and the remote rehearsal passed.

**Comment by vmarkovtsev** [comment]
@vcoisne The talk was given. My mark is 4/5, according to the feedback sent by the organizers.
5O8A1165

**Comment by bzz** [comment]
@vcoisne seems like it is ready to be merged.

**Review by vcoisne — APPROVED** [review]
LGTM

**Pull request merged**
