### PR TITLE
2018/25 - GopherCon Russia - Measuring code sentiment in a Git repository

### PR DESCRIPTION
**Pull request by vmarkovtsev**
# GopherCon Russia - Measuring code sentiment in a Git repository

Updates: https://github.com/src-d/conferences/issues/19

### CODE REVIEW

**Comment by campoy** [comment]
Please follow [this PR format](https://github.com/src-d/conferences/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by campoy** [comment]
Hey @vmarkovtsev, would you mind following the PR format linked above?
Thanks!

**Comment by vmarkovtsev** [comment]
@campoy Done. AFAIR I was confused by https://github.com/src-d/conferences/issues/20

**Review by campoy — APPROVED** [review]
I'm not going to review abstracts in Russian for now ... 😄

**Pull request merged**
