### PR TITLE
2018/07 - PyData Berlin - Machine Learning on Source Code

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>

Updates: https://github.com/src-d/conferences/issues/31

### CODE REVIEW

**Comment by campoy** [comment]
Was this accepted? Please update the description and I'll approve

**Comment by vmarkovtsev** [comment]
@campoy They have not announced their decision yet.

**Comment by vmarkovtsev** [comment]
Update: they are still deciding.

**Comment by campoy** [comment]
update, @vmarkovtsev ?

**Pull request closed without merging**
